# Generated by Django 4.1.1 on 2022-09-16 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0003_rename_user_persona_credenciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='credenciales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
